app:
  user: callboard
  password: 456852
  host: 172.16.30.48
  port: 5038
  db_host: 172.16.30.48
  db_user: asterisk-admin
  db_password: Qrtp80%tvbMkt
  db_name: asterisk_1
  redis_host: 172.16.255.10
  redis_user: admin2
  redis_pssword: kukla
  redis_db: 1
  rabbitmq_host: 172.16.255.10
  rabbitmq_username: admin2
  rabbitmq_password: kukla
spring:
  main:
    banner-mode: "off"
server:
  port: 9898
logging:
  file: /var/log/web-callboard.log
